apiVersion: v1
kind: Service
metadata:
  name: result 
  labels:
    app: result
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  ports:
  - name: "result-service"
    port: 80
    targetPort: 80
  selector:
    app: result
