apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    app: vote
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer 
  ports:
  - name: "vote-service"
    port: 80
    targetPort: 80
  selector:
    app: vote
